workspace:
  base: /go/src
  path: github.com/appleboy/gin-jwt

pipeline:
  build:
    image: appleboy/golang-testing:${GO_VERSION}
    secrets: [ codecov_token ]
    commands:
      - make install
      - make embedmd
      - make vet
      - make lint
      - coverage all
      - make coverage

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]

matrix:
  GO_VERSION:
    - 1.8.4
    - 1.9.1
